name: thesis
channels:
  - defaults
  - conda-forge
dependencies:
  - anyio=4.7.0
  - aom=3.6.0
  - appnope=0.1.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - audioread=3.0.1
  - babel=2.16.0
  - beautifulsoup4=4.13.4
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.16.0
  - certifi=2026.1.4
  - cffi=1.17.1
  - charset-normalizer=3.4.4
  - choreographer=1.2.1
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - debugpy=1.8.11
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.7.1
  - ffmpeg=4.3.2
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - fribidi=1.0.10
  - gettext=0.21.0
  - gmp=6.3.0
  - gnutls=3.6.13
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=10.2.0
  - hdbscan=0.8.41
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.11
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - iniconfig=2.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - ipywidgets=8.1.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.16
  - kiwisolver=1.4.8
  - lame=3.100
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libcxx=19.1.7
  - libdeflate=1.22
  - libffi=3.4.4
  - libflac=1.4.1
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.84.2
  - libhwloc=2.12.1
  - libiconv=1.16
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopus=1.6.1
  - libpng=1.6.39
  - librosa=0.9.2
  - libsndfile=1.1.0
  - libsodium=1.0.18
  - libtiff=4.7.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - llvm-openmp=19.1.7
  - llvmlite=0.44.0
  - logistro=2.0.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mistune=3.1.2
  - mpg123=1.30.2
  - narwhals=2.15.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.6
  - notebook=7.4.4
  - notebook-shim=0.2.4
  - numba=0.61.0
  - numexpr=2.11.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.6.1
  - orjson=3.11.5
  - overrides=7.4.0
  - packaging=25.0
  - pandas=2.3.1
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pillow=11.3.0
  - pixman=0.46.4
  - platformdirs=4.5.1
  - plotly=6.5.2
  - pluggy=1.5.0
  - pooch=1.9.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycatch22=0.4.5
  - pycparser=2.22
  - pygments=2.19.1
  - pynndescent=0.5.13
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - pysoundfile=0.11.0
  - pytest=8.4.1
  - pytest-timeout=2.4.0
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-kaleido=1.2.0
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.3
  - referencing=0.30.2
  - requests=2.32.5
  - resampy=0.4.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - scikit-learn=1.7.1
  - scipy=1.15.3
  - seaborn=0.13.2
  - send2trash=1.8.2
  - session-info=1.0.0
  - simplejson=3.20.2
  - six=1.17.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.50.2
  - stack_data=0.2.0
  - stdlib-list=0.12.0
  - tbb=2022.3.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.1
  - tqdm=4.67.2
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025c
  - umap-learn=0.5.11
  - unicodedata2=15.1.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - x264=1!161.3030
  - xz=5.6.4
  - yaml=0.2.5
  - yellowbrick=1.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - pip==24.3.1
      - setuptools==44.1.1
prefix: /opt/miniconda3/envs/thesis